# Dockerfile.streamlit
# Separated Dockefiles for UI and FastAPI to prevent mixing UI and backend logic
FROM --platform=$BUILDPLATFORM python:3.11-slim

ENV PYTHONUNBUFFERED=1 PIP_NO_CACHE_DIR=1
WORKDIR /app

COPY pyproject.toml poetry.lock* ./
RUN pip install --no-cache-dir poetry
RUN poetry config virtualenvs.create false \
  && poetry install --only main --no-interaction --no-ansi --no-root

COPY . .

# Streamlist config
ENV STREAMLIT_SERVER_PORT=8501 \
    STREAMLIT_SERVER_ADDRESS=0.0.0.0 \
    STREAMLIT_SERVER_BASEURLPATH=/dashboard \
    STREAMLIT_BROWSER_GATHERUSAGESTATS=false

# Default API_URL (override in docker run)
ENV API_URL=http://localhost:8000/predict

EXPOSE 8501

# Ensure that streamlit is what's starting
ENTRYPOINT [ "streamlit", "run", "app.py" ]
# here CMD is used to define the default parameters to ENTRYPOINT
CMD ["--server.port=8501", "--server.address=0.0.0.0", "--server.baseUrlPath=/dashboard"]